version: '3.8'
services:
  mariadb:
    container_name: mariadb_container
    image: mariadb
    ports:
      - "13306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mydata:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - mjc_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  boot-app:
    image: asjcell/backend_image:v1.1.7
    container_name: boot_container
    ports:
      - "18888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: prod  # 가장 중요!
      TZ: Asia/Seoul
      # MariaDB 환경 변수 (필수!)
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      # Mail 설정
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      # JWT 설정
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      # OAuth 설정
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
    depends_on:
      mariadb:
        condition: service_healthy  # MariaDB가 준비될 때까지 대기
    networks:
      - mjc_network

  front-app:
    image: dldptj/front_image:v1.0.12
    container_name: front_container
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - boot-app
    networks:
      - mjc_network

networks:
  mjc_network:
    driver: bridge